packages:
  - .
  - docs
  - packages/*
packageExtensions:
  "@nolebase/vitepress-plugin-highlight-targeted-heading":
    peerDependencies:
      vue: "^3.5.32"
      "@vueuse/core": "^14.2.1"
  "vitepress-plugin-pagefind":
    peerDependencies:
      vue: "^3.5.32"
  "vue-command-palette":
    peerDependencies:
      vue: "^3.5.32"
trustPolicy: no-downgrade
hoist: false
engineStrict: true # engines.node will be strictly enforced when installing dependencies
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
shellEmulator: true
