packages:
  - .
  - docs
  - packages/*
packageExtensions:
  "@nolebase/vitepress-plugin-highlight-targeted-heading":
    peerDependencies:
      vue: "*"
      "@vueuse/core": "*"
  "vitepress-plugin-pagefind":
    peerDependencies:
      vue: "*"
  "vue-command-palette":
    peerDependencies:
      vue: "*"
trustPolicy: no-downgrade
hoist: false
engineStrict: true # engines.node will be strictly enforced when installing dependencies
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
shellEmulator: true
