export const DETECTION_TASK_BOUNDS_ONLY: u32 = 1;
export const DETECTION_TASK_AUTO: u32 = 2;
export const DETECTION_TASK_KNOWN_BOUNDS: u32 = 3;

export const DETECTION_INPUT_TASK_OFFSET: u32 = 0;
export const DETECTION_INPUT_WIDTH_OFFSET: u32 = 4;
export const DETECTION_INPUT_HEIGHT_OFFSET: u32 = 8;
export const DETECTION_INPUT_RGBA_POINTER_OFFSET: u32 = 12;
export const DETECTION_INPUT_RGBA_BYTE_LENGTH_OFFSET: u32 = 16;
export const DETECTION_INPUT_SETTINGS_POINTER_OFFSET: u32 = 20;
export const DETECTION_INPUT_SETTINGS_LENGTH_OFFSET: u32 = 24;
export const DETECTION_INPUT_EDGE_POINTER_OFFSET: u32 = 28;
export const DETECTION_INPUT_EDGE_LENGTH_OFFSET: u32 = 32;
export const DETECTION_INPUT_RESERVED_OFFSET: u32 = 36;
export const DETECTION_INPUT_BYTE_LENGTH: u32 = 40;

export const DETECTION_RESULT_COMPLETE: u32 = 1;
export const DETECTION_RESULT_RUNNING: u32 = 2;
export const DETECTION_RESULT_FLAG_HAS_EDGE_RECT: u32 = 1;

export const DETECTION_RESULT_STATE_OFFSET: u32 = 0;
export const DETECTION_RESULT_TASK_OFFSET: u32 = 4;
export const DETECTION_RESULT_FLAGS_OFFSET: u32 = 8;
export const DETECTION_RESULT_STAGE_POINTER_OFFSET: u32 = 12;
export const DETECTION_RESULT_STAGE_COUNT_OFFSET: u32 = 16;
export const DETECTION_RESULT_SESSION_POINTER_OFFSET: u32 = 20;
export const DETECTION_RESULT_WORK_POINTER_OFFSET: u32 = 24;
export const DETECTION_RESULT_WORK_COUNT_OFFSET: u32 = 28;
export const DETECTION_RESULT_EDGE_X_OFFSET: u32 = 32;
export const DETECTION_RESULT_EDGE_Y_OFFSET: u32 = 40;
export const DETECTION_RESULT_EDGE_WIDTH_OFFSET: u32 = 48;
export const DETECTION_RESULT_EDGE_HEIGHT_OFFSET: u32 = 56;
export const DETECTION_RESULT_BYTE_LENGTH: u32 = 64;

export const DETECTION_STAGE_BOUNDS_START: u32 = 1;
export const DETECTION_STAGE_BOUNDS_END: u32 = 2;
