export const ROUTE_COMMAND_CREATE_CONTEXT: u32 = 1;
export const ROUTE_COMMAND_POINT_HIT: u32 = 2;
export const ROUTE_COMMAND_LINE_HIT: u32 = 3;
export const ROUTE_COMMAND_GRAPH_REGION_HIT: u32 = 4;
export const ROUTE_COMMAND_PLANE_REGION_COUNT: u32 = 5;
export const ROUTE_COMMAND_THETA_STAR: u32 = 6;
export const ROUTE_COMMAND_VISIBILITY_GRAPH: u32 = 7;
export const ROUTE_COMMAND_STEP_TRANSITION: u32 = 8;
export const ROUTE_COMMAND_STEP_THETA_STAR: u32 = 9;
export const ROUTE_COMMAND_STEP_VISIBILITY_GRAPH: u32 = 10;
/** Intern canonical `(target, Step state)` identities for one-click DAG discovery. */
// Route commands 1..10 and Step-glitch commands 11..20 share runRouteTask;
// keep this extension outside both existing command ranges.
export const ROUTE_COMMAND_ONE_CLICK_STEP_STATE_DEDUP: u32 = 21;
export const ONE_CLICK_STEP_STATE_DEDUP_MAGIC: u32 = 0x4f_4344_50;
export const ONE_CLICK_STEP_STATE_DEDUP_VERSION: u32 = 1;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_TARGET_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_OFFSET_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_KEY_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_KEY_LENGTH_OFFSET: u32 = 20;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_RESOLVED_Y_POINTER_OFFSET: u32 = 24;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_KEY_BYTE_LENGTH_OFFSET: u32 = 32;
export const ONE_CLICK_STEP_STATE_DEDUP_INPUT_BYTE_LENGTH: u32 = 40;
export const ONE_CLICK_STEP_STATE_DEDUP_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_STEP_STATE_DEDUP_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_STEP_STATE_DEDUP_RESULT_NODE_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_STEP_STATE_DEDUP_RESULT_NODE_COUNT_OFFSET: u32 = 12;
export const ONE_CLICK_STEP_STATE_DEDUP_RESULT_BYTE_LENGTH: u32 = 16;
/** Expand one bounded layer of the stateful one-click Step DAG into stable edge descriptors. */
export const ROUTE_COMMAND_ONE_CLICK_STEP_DAG_EXPAND: u32 = 22;
export const ONE_CLICK_STEP_DAG_EXPAND_MAGIC: u32 = 0x4f_434a_45;
export const ONE_CLICK_STEP_DAG_EXPAND_VERSION: u32 = 1;
export const ONE_CLICK_STEP_DAG_EXPAND_FLAG_START: u32 = 1;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_FLAGS_OFFSET: u32 = 8;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_TARGET_X_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_TARGET_Y_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_TARGET_GRAPH_X_POINTER_OFFSET: u32 = 20;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_TARGET_COUNT_OFFSET: u32 = 24;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_SOURCE_NODE_IDS_POINTER_OFFSET: u32 = 28;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_SOURCE_TARGETS_POINTER_OFFSET: u32 = 32;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_SOURCE_COUNT_OFFSET: u32 = 36;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_START_X_OFFSET: u32 = 40;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_START_Y_OFFSET: u32 = 48;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_NODE_COUNT_OFFSET: u32 = 56;
export const ONE_CLICK_STEP_DAG_EXPAND_INPUT_BYTE_LENGTH: u32 = 64;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_ID_OFFSET: u32 = 0;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_FROM_NODE_OFFSET: u32 = 4;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_FROM_TARGET_OFFSET: u32 = 8;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_TO_TARGET_OFFSET: u32 = 12;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_START_X_OFFSET: u32 = 16;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_START_Y_OFFSET: u32 = 24;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_TARGET_X_OFFSET: u32 = 32;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_TARGET_Y_OFFSET: u32 = 40;
export const ONE_CLICK_STEP_DAG_EXPAND_JOB_BYTE_LENGTH: u32 = 48;
export const ONE_CLICK_STEP_DAG_EXPAND_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_STEP_DAG_EXPAND_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_STEP_DAG_EXPAND_RESULT_JOB_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_STEP_DAG_EXPAND_RESULT_JOB_COUNT_OFFSET: u32 = 12;
export const ONE_CLICK_STEP_DAG_EXPAND_RESULT_BYTE_LENGTH: u32 = 16;
/** Validate a complete Step route below the retained context in one command. */
export const ROUTE_COMMAND_STEP_PATH_VALIDATION: u32 = 23;
/** Compare one-click incumbent candidates without reimplementing tie-breaks in the effective WASM path. */
export const ROUTE_COMMAND_ONE_CLICK_INCUMBENT_COMPARE: u32 = 24;
export const ONE_CLICK_INCUMBENT_COMPARE_MAGIC: u32 = 0x4f_4349_43;
export const ONE_CLICK_INCUMBENT_COMPARE_VERSION: u32 = 1;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CANDIDATE_TARGET_COUNT_OFFSET: u32 = 8;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CANDIDATE_POINT_COUNT_OFFSET: u32 = 12;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CANDIDATE_PATH_ERROR_OFFSET: u32 = 16;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CANDIDATE_PATH_ERROR_FLAG_OFFSET: u32 = 24;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CURRENT_TARGET_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CURRENT_POINT_COUNT_OFFSET: u32 = 32;
/** Padding before the aligned current path-error f64; must stay zero across the raw ABI. */
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_ALIGNMENT_RESERVED_OFFSET: u32 = 36;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CURRENT_PATH_ERROR_OFFSET: u32 = 40;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_CURRENT_PATH_ERROR_FLAG_OFFSET: u32 = 48;
/** Tail word reserved for future comparator inputs; validate it before using the record. */
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_RESERVED_OFFSET: u32 = 52;
export const ONE_CLICK_INCUMBENT_COMPARE_INPUT_BYTE_LENGTH: u32 = 56;
export const ONE_CLICK_INCUMBENT_COMPARE_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_INCUMBENT_COMPARE_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_INCUMBENT_COMPARE_RESULT_RESERVED_OFFSET: u32 = 8;
export const ONE_CLICK_INCUMBENT_COMPARE_RESULT_BYTE_LENGTH: u32 = 12;
/** Retain one request's incumbent score and event sequence below the WASM boundary. */
export const ROUTE_COMMAND_ONE_CLICK_INCUMBENT_EVENT: u32 = 25;
export const ONE_CLICK_INCUMBENT_EVENT_MAGIC: u32 = 0x4f_4349_45;
export const ONE_CLICK_INCUMBENT_EVENT_VERSION: u32 = 1;
export const ONE_CLICK_INCUMBENT_EVENT_BEGIN_OPERATION: u32 = 1;
export const ONE_CLICK_INCUMBENT_EVENT_CONSIDER_OPERATION: u32 = 2;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_OPERATION_OFFSET: u32 = 8;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_SESSION_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_REQUEST_NONCE_OFFSET: u32 = 16;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_ATTEMPT_ID_OFFSET: u32 = 20;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_GENERATION_OFFSET: u32 = 24;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_OUTER_TASK_ID_OFFSET: u32 = 28;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_CANDIDATE_TARGET_COUNT_OFFSET: u32 = 32;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_CANDIDATE_POINT_COUNT_OFFSET: u32 = 36;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_CANDIDATE_PATH_ERROR_OFFSET: u32 = 40;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_CANDIDATE_PATH_ERROR_FLAG_OFFSET: u32 = 48;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_RESERVED_OFFSET: u32 = 52;
export const ONE_CLICK_INCUMBENT_EVENT_INPUT_BYTE_LENGTH: u32 = 56;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_VERSION_OFFSET: u32 = 4;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_REQUEST_NONCE_OFFSET: u32 = 8;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_ATTEMPT_ID_OFFSET: u32 = 12;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_GENERATION_OFFSET: u32 = 16;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_OUTER_TASK_ID_OFFSET: u32 = 20;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_SEQUENCE_OFFSET: u32 = 24;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_BEST_TARGET_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_BEST_POINT_COUNT_OFFSET: u32 = 32;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_BEST_PATH_ERROR_OFFSET: u32 = 40;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_BEST_PATH_ERROR_FLAG_OFFSET: u32 = 48;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_RESERVED_OFFSET: u32 = 52;
export const ONE_CLICK_INCUMBENT_EVENT_SESSION_BYTE_LENGTH: u32 = 56;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_SEQUENCE_OFFSET: u32 = 8;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_SESSION_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_RESERVED_OFFSET: u32 = 16;
export const ONE_CLICK_INCUMBENT_EVENT_RESULT_BYTE_LENGTH: u32 = 20;
export {
  STEP_GLITCH_COMMAND_CREATE_CONTEXT,
  STEP_GLITCH_COMMAND_PREPARE_CANDIDATE_FORMULA_FOR_TEST,
  STEP_GLITCH_COMMAND_REPLAY_CANDIDATE_FOR_TEST,
  STEP_GLITCH_COMMAND_REPLAY_TRAJECTORY_FOR_TEST,
  STEP_GLITCH_COMMAND_TRACE_REAL_DFS_FOR_TEST,
  STEP_GLITCH_COMMAND_TRACE_DFS,
  STEP_GLITCH_COMMAND_TRACE_FRONTIER,
  STEP_GLITCH_COMMAND_SCAN,
  STEP_GLITCH_COMMAND_REPLAY,
  STEP_GLITCH_COMMAND_COMPOSE_SMART_PATH,
  STEP_GLITCH_COMMAND_COMPOSE_ONE_CLICK_SESSION,
} from "./step-glitch-layout";

export const ROUTE_CREATE_SOURCE_MASK_POINTER_OFFSET: u32 = 0;
export const ROUTE_CREATE_SOURCE_MASK_LENGTH_OFFSET: u32 = 4;
export const ROUTE_CREATE_CONTEXT_VALUES_POINTER_OFFSET: u32 = 8;
export const ROUTE_CREATE_CONTEXT_VALUES_LENGTH_OFFSET: u32 = 12;
export const ROUTE_CREATE_FRIENDLY_X_POINTER_OFFSET: u32 = 16;
export const ROUTE_CREATE_FRIENDLY_Y_POINTER_OFFSET: u32 = 20;
export const ROUTE_CREATE_FRIENDLY_COUNT_OFFSET: u32 = 24;
export const ROUTE_CREATE_POLICY_POINTER_OFFSET: u32 = 28;
export const ROUTE_CREATE_POLICY_LENGTH_OFFSET: u32 = 32;
export const ROUTE_CREATE_LOOKAHEAD_POINTER_OFFSET: u32 = 36;
export const ROUTE_CREATE_LOOKAHEAD_LENGTH_OFFSET: u32 = 40;
export const ROUTE_CREATE_STEP_MODEL_POINTER_OFFSET: u32 = 44;
export const ROUTE_CREATE_FLAGS_OFFSET: u32 = 48;
export const ROUTE_CREATE_FLAG_PREPROCESSED_ROUTE_MASK: u32 = 1;
export const ROUTE_CREATE_INPUT_BYTE_LENGTH: u32 = 52;

export const ROUTE_STEP_MODEL_ORIGIN_Y_OFFSET: u32 = 0;
export const ROUTE_STEP_MODEL_FORMULA_STEEPNESS_OFFSET: u32 = 8;
export const ROUTE_STEP_MODEL_QUALITY_TARGET_PLANE_PIXELS_OFFSET: u32 = 16;
export const ROUTE_STEP_MODEL_DECIMAL_PLACES_OFFSET: u32 = 24;
export const ROUTE_STEP_MODEL_EQUATION_OFFSET: u32 = 32;
export const ROUTE_STEP_MODEL_BYTE_LENGTH: u32 = 40;

export const ROUTE_CONTEXT_VALUE_MIN_X_INDEX: u32 = 0;
export const ROUTE_CONTEXT_VALUE_MAX_X_INDEX: u32 = 1;
export const ROUTE_CONTEXT_VALUE_MIN_Y_INDEX: u32 = 2;
export const ROUTE_CONTEXT_VALUE_MAX_Y_INDEX: u32 = 3;
export const ROUTE_CONTEXT_VALUE_RECT_X_INDEX: u32 = 4;
export const ROUTE_CONTEXT_VALUE_RECT_Y_INDEX: u32 = 5;
export const ROUTE_CONTEXT_VALUE_RECT_WIDTH_INDEX: u32 = 6;
export const ROUTE_CONTEXT_VALUE_RECT_HEIGHT_INDEX: u32 = 7;
export const ROUTE_CONTEXT_VALUE_BOUNDARY_EXPANSION_INDEX: u32 = 8;
export const ROUTE_CONTEXT_VALUE_ROUTE_TOLERANCE_INDEX: u32 = 9;
export const ROUTE_CONTEXT_VALUE_SIMULATION_TOLERANCE_INDEX: u32 = 10;
export const ROUTE_CONTEXT_VALUE_ORIGIN_X_INDEX: u32 = 11;
export const ROUTE_CONTEXT_VALUE_ORIGIN_Y_INDEX: u32 = 12;
export const ROUTE_CONTEXT_VALUE_SOLDIER_HIT_RADIUS_INDEX: u32 = 13;
export const ROUTE_CONTEXT_VALUE_COUNT: u32 = 14;

export const ROUTE_CONTEXT_MAGIC: u32 = 0x524f_5554;
export const ROUTE_CONTEXT_FLAG_MIRRORED: u32 = 1;
export const ROUTE_CONTEXT_FLAG_STEP_MODEL: u32 = 2;
export const ROUTE_CONTEXT_FLAG_PREPROCESSED_ROUTE_MASK: u32 = 4;
export const ROUTE_CONTEXT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_CONTEXT_FLAGS_OFFSET: u32 = 4;
export const ROUTE_CONTEXT_ROUTE_MASK_POINTER_OFFSET: u32 = 8;
export const ROUTE_CONTEXT_ROUTE_MASK_LENGTH_OFFSET: u32 = 12;
export const ROUTE_CONTEXT_SIMULATION_MASK_POINTER_OFFSET: u32 = 16;
export const ROUTE_CONTEXT_SIMULATION_MASK_LENGTH_OFFSET: u32 = 20;
export const ROUTE_CONTEXT_SUMMED_AREA_POINTER_OFFSET: u32 = 24;
export const ROUTE_CONTEXT_SUMMED_AREA_LENGTH_OFFSET: u32 = 28;
export const ROUTE_CONTEXT_ROUTE_OBSTACLE_COUNT_OFFSET: u32 = 32;
export const ROUTE_CONTEXT_SIMULATION_OBSTACLE_COUNT_OFFSET: u32 = 36;
export const ROUTE_CONTEXT_COMPONENT_COUNT_OFFSET: u32 = 40;
export const ROUTE_CONTEXT_BOUNDARY_EDGE_COUNT_OFFSET: u32 = 44;
export const ROUTE_CONTEXT_COMPONENT_IDS_POINTER_OFFSET: u32 = 48;
export const ROUTE_CONTEXT_COMPONENT_IDS_LENGTH_OFFSET: u32 = 52;
export const ROUTE_CONTEXT_BOUNDARY_EDGES_POINTER_OFFSET: u32 = 56;
export const ROUTE_CONTEXT_BOUNDARY_EDGES_LENGTH_OFFSET: u32 = 60;
export const ROUTE_CONTEXT_MIN_X_OFFSET: u32 = 64;
export const ROUTE_CONTEXT_MAX_X_OFFSET: u32 = 72;
export const ROUTE_CONTEXT_MIN_Y_OFFSET: u32 = 80;
export const ROUTE_CONTEXT_MAX_Y_OFFSET: u32 = 88;
export const ROUTE_CONTEXT_BOUNDARY_EXPANSION_OFFSET: u32 = 96;
export const ROUTE_CONTEXT_ORIGIN_X_OFFSET: u32 = 104;
export const ROUTE_CONTEXT_ORIGIN_Y_OFFSET: u32 = 112;
export const ROUTE_CONTEXT_ROUTE_TOLERANCE_OFFSET: u32 = 120;
export const ROUTE_CONTEXT_SIMULATION_TOLERANCE_OFFSET: u32 = 128;
export const ROUTE_CONTEXT_POLICY_POINTER_OFFSET: u32 = 136;
export const ROUTE_CONTEXT_POLICY_LENGTH_OFFSET: u32 = 140;
export const ROUTE_CONTEXT_LOOKAHEAD_POINTER_OFFSET: u32 = 144;
export const ROUTE_CONTEXT_LOOKAHEAD_LENGTH_OFFSET: u32 = 148;
export const ROUTE_CONTEXT_FREE_SPAN_OFFSETS_POINTER_OFFSET: u32 = 152;
export const ROUTE_CONTEXT_FREE_SPAN_OFFSETS_LENGTH_OFFSET: u32 = 156;
export const ROUTE_CONTEXT_FREE_SPAN_VALUES_POINTER_OFFSET: u32 = 160;
export const ROUTE_CONTEXT_FREE_SPAN_VALUES_LENGTH_OFFSET: u32 = 164;
export const ROUTE_CONTEXT_THETA_CLOSED_POINTER_OFFSET: u32 = 168;
export const ROUTE_CONTEXT_THETA_G_SCORE_POINTER_OFFSET: u32 = 172;
export const ROUTE_CONTEXT_THETA_PARENT_POINTER_OFFSET: u32 = 176;
export const ROUTE_CONTEXT_THETA_TOUCHED_POINTER_OFFSET: u32 = 180;
export const ROUTE_CONTEXT_THETA_TOUCHED_COUNT_OFFSET: u32 = 184;
export const ROUTE_CONTEXT_THETA_CANDIDATES_POINTER_OFFSET: u32 = 188;
export const ROUTE_CONTEXT_THETA_SEEN_POINTER_OFFSET: u32 = 192;
export const ROUTE_CONTEXT_THETA_PREVIEW_CANDIDATE_LIMIT_OFFSET: u32 = 196;
export const ROUTE_CONTEXT_THETA_PREVIEW_EDGE_LIMIT_OFFSET: u32 = 200;
export const ROUTE_CONTEXT_THETA_PREVIEW_EXPANSION_INTERVAL_OFFSET: u32 = 204;
export const ROUTE_CONTEXT_VISIBILITY_COMPONENT_STATS_POINTER_OFFSET: u32 = 208;
export const ROUTE_CONTEXT_VISIBILITY_COMPONENT_STATS_LENGTH_OFFSET: u32 = 212;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_OFFSETS_POINTER_OFFSET: u32 = 216;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_OFFSETS_LENGTH_OFFSET: u32 = 220;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_COMPONENTS_POINTER_OFFSET: u32 = 224;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_X_POINTER_OFFSET: u32 = 228;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_Y_POINTER_OFFSET: u32 = 232;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_SIGNED_AREAS_POINTER_OFFSET: u32 = 236;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_COUNT_OFFSET: u32 = 240;
export const ROUTE_CONTEXT_VISIBILITY_CONTOUR_POINT_COUNT_OFFSET: u32 = 244;
export const ROUTE_CONTEXT_VISIBILITY_PREVIEW_CANDIDATE_LIMIT_OFFSET: u32 = 248;
export const ROUTE_CONTEXT_VISIBILITY_PREVIEW_EDGE_LIMIT_OFFSET: u32 = 252;
export const ROUTE_CONTEXT_VISIBILITY_PREVIEW_EXPANSION_INTERVAL_OFFSET: u32 = 256;
export const ROUTE_CONTEXT_STEP_MODEL_POINTER_OFFSET: u32 = 260;
export const ROUTE_CONTEXT_BYTE_LENGTH: u32 = 264;

export const ROUTE_POLICY_VISIBILITY_CONCAVE_CROSS_TOLERANCE_INDEX: u32 = 0;
export const ROUTE_POLICY_VISIBILITY_COLLINEAR_DISTANCE_TOLERANCE_INDEX: u32 = 1;
export const ROUTE_POLICY_VISIBILITY_FREE_CELL_SEARCH_RADIUS_INDEX: u32 = 2;
export const ROUTE_POLICY_VISIBILITY_RDP_TOLERANCE_RATIO_INDEX: u32 = 3;
export const ROUTE_POLICY_VISIBILITY_RDP_MAX_EPSILON_INDEX: u32 = 4;
export const ROUTE_POLICY_VISIBILITY_RDP_MIN_EPSILON_INDEX: u32 = 5;
export const ROUTE_POLICY_VISIBILITY_PREVIEW_CANDIDATE_LIMIT_INDEX: u32 = 6;
export const ROUTE_POLICY_VISIBILITY_PREVIEW_EDGE_LIMIT_INDEX: u32 = 7;
export const ROUTE_POLICY_VISIBILITY_PREVIEW_EXPANSION_INTERVAL_INDEX: u32 = 8;
export const ROUTE_POLICY_THETA_PREVIEW_CANDIDATE_LIMIT_INDEX: u32 = 9;
export const ROUTE_POLICY_THETA_PREVIEW_EDGE_LIMIT_INDEX: u32 = 10;
export const ROUTE_POLICY_THETA_PREVIEW_EXPANSION_INTERVAL_INDEX: u32 = 11;

export const ROUTE_POINT_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_POINT_INPUT_X_OFFSET: u32 = 8;
export const ROUTE_POINT_INPUT_Y_OFFSET: u32 = 16;
export const ROUTE_POINT_INPUT_BYTE_LENGTH: u32 = 24;

export const ROUTE_LINE_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_LINE_INPUT_START_X_OFFSET: u32 = 8;
export const ROUTE_LINE_INPUT_START_Y_OFFSET: u32 = 16;
export const ROUTE_LINE_INPUT_END_X_OFFSET: u32 = 24;
export const ROUTE_LINE_INPUT_END_Y_OFFSET: u32 = 32;
export const ROUTE_LINE_INPUT_BYTE_LENGTH: u32 = 40;

export const ROUTE_REGION_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_REGION_INPUT_MIN_X_OFFSET: u32 = 8;
export const ROUTE_REGION_INPUT_MAX_X_OFFSET: u32 = 16;
export const ROUTE_REGION_INPUT_MIN_Y_OFFSET: u32 = 24;
export const ROUTE_REGION_INPUT_MAX_Y_OFFSET: u32 = 32;
export const ROUTE_REGION_INPUT_BYTE_LENGTH: u32 = 40;

export const ROUTE_QUERY_RESULT_MAGIC: u32 = 0x5152_4f55;
export const ROUTE_QUERY_RESULT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_QUERY_RESULT_VALUE_OFFSET: u32 = 4;
export const ROUTE_QUERY_RESULT_BYTE_LENGTH: u32 = 8;

export const ROUTE_SEARCH_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_SEARCH_INPUT_START_X_OFFSET: u32 = 8;
export const ROUTE_SEARCH_INPUT_START_Y_OFFSET: u32 = 16;
export const ROUTE_SEARCH_INPUT_TARGET_X_OFFSET: u32 = 24;
export const ROUTE_SEARCH_INPUT_TARGET_Y_OFFSET: u32 = 32;
export const ROUTE_SEARCH_INPUT_COLLECT_PREVIEWS_OFFSET: u32 = 40;
export const ROUTE_SEARCH_INPUT_BYTE_LENGTH: u32 = 48;

export const ROUTE_SEARCH_RESULT_MAGIC: u32 = 0x5253_4c54;
export const ROUTE_SEARCH_RESULT_STATUS_NO_ROUTE: u32 = 0;
export const ROUTE_SEARCH_RESULT_STATUS_SUCCESS: u32 = 1;
export const ROUTE_SEARCH_RESULT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_SEARCH_RESULT_STATUS_OFFSET: u32 = 4;
export const ROUTE_SEARCH_RESULT_PATH_X_POINTER_OFFSET: u32 = 8;
export const ROUTE_SEARCH_RESULT_PATH_Y_POINTER_OFFSET: u32 = 12;
export const ROUTE_SEARCH_RESULT_PATH_LENGTH_OFFSET: u32 = 16;
export const ROUTE_SEARCH_RESULT_PREVIEW_POINTER_OFFSET: u32 = 20;
export const ROUTE_SEARCH_RESULT_PREVIEW_COUNT_OFFSET: u32 = 24;
export const ROUTE_SEARCH_RESULT_EXPANSION_COUNT_OFFSET: u32 = 28;
export const ROUTE_SEARCH_RESULT_BYTE_LENGTH: u32 = 32;

export const ROUTE_STEP_TRANSITION_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_STEP_TRANSITION_INPUT_PREVIOUS_X_OFFSET: u32 = 8;
export const ROUTE_STEP_TRANSITION_INPUT_PREVIOUS_Y_OFFSET: u32 = 16;
export const ROUTE_STEP_TRANSITION_INPUT_NEXT_X_OFFSET: u32 = 24;
export const ROUTE_STEP_TRANSITION_INPUT_NEXT_Y_OFFSET: u32 = 32;
export const ROUTE_STEP_TRANSITION_INPUT_RESOLVED_Y_OFFSET: u32 = 40;
export const ROUTE_STEP_TRANSITION_INPUT_STATE_SIGN_OFFSET: u32 = 48;
export const ROUTE_STEP_TRANSITION_INPUT_STATE_POINTER_OFFSET: u32 = 52;
export const ROUTE_STEP_TRANSITION_INPUT_STATE_COUNT_OFFSET: u32 = 56;
export const ROUTE_STEP_TRANSITION_INPUT_BYTE_LENGTH: u32 = 64;

export const ROUTE_STEP_TRANSITION_RESULT_MAGIC: u32 = 0x5354_4550;
export const ROUTE_STEP_TRANSITION_STATUS_SUCCESS: u32 = 0;
export const ROUTE_STEP_TRANSITION_STATUS_NON_FORWARD: u32 = 1;
export const ROUTE_STEP_TRANSITION_STATUS_NUMERIC: u32 = 2;
export const ROUTE_STEP_TRANSITION_STATUS_CENTER_OUTSIDE_SEGMENT: u32 = 3;
export const ROUTE_STEP_TRANSITION_STATUS_SYMMETRIC_START_BEFORE_SEGMENT: u32 = 4;
export const ROUTE_STEP_TRANSITION_STATUS_OBSTACLE: u32 = 5;
export const ROUTE_STEP_TRANSITION_STATUS_NON_FINITE: u32 = 6;
export const ROUTE_STEP_TRANSITION_RESULT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_STEP_TRANSITION_RESULT_STATUS_OFFSET: u32 = 4;
export const ROUTE_STEP_TRANSITION_RESULT_RESOLVED_START_Y_OFFSET: u32 = 8;
export const ROUTE_STEP_TRANSITION_RESULT_RESOLVED_END_Y_OFFSET: u32 = 16;
export const ROUTE_STEP_TRANSITION_RESULT_SECONDARY_COST_OFFSET: u32 = 24;
export const ROUTE_STEP_TRANSITION_RESULT_XS_OFFSET: u32 = 32;
export const ROUTE_STEP_TRANSITION_RESULT_YM_OFFSET: u32 = 40;
export const ROUTE_STEP_TRANSITION_RESULT_H_OFFSET: u32 = 48;
export const ROUTE_STEP_TRANSITION_RESULT_R0_OFFSET: u32 = 80;
export const ROUTE_STEP_TRANSITION_RESULT_R1_OFFSET: u32 = 112;
export const ROUTE_STEP_TRANSITION_RESULT_STATE_SIGN_OFFSET: u32 = 144;
export const ROUTE_STEP_TRANSITION_RESULT_STATE_POINTER_OFFSET: u32 = 148;
export const ROUTE_STEP_TRANSITION_RESULT_STATE_COUNT_OFFSET: u32 = 152;
export const ROUTE_STEP_TRANSITION_RESULT_BYTE_LENGTH: u32 = 160;

export const ROUTE_STEP_PATH_VALIDATION_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_STEP_PATH_VALIDATION_INPUT_GRAPH_X_POINTER_OFFSET: u32 = 8;
export const ROUTE_STEP_PATH_VALIDATION_INPUT_GRAPH_Y_POINTER_OFFSET: u32 = 12;
export const ROUTE_STEP_PATH_VALIDATION_INPUT_POINT_COUNT_OFFSET: u32 = 16;
export const ROUTE_STEP_PATH_VALIDATION_INPUT_BYTE_LENGTH: u32 = 24;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_MAGIC: u32 = 0x5354_5056;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_STATUS_OFFSET: u32 = 4;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_INVALID_SEGMENT_INDEX_OFFSET: u32 = 8;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_RESOLVED_END_Y_OFFSET: u32 = 16;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_STATE_SIGN_OFFSET: u32 = 24;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_STATE_POINTER_OFFSET: u32 = 28;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_STATE_COUNT_OFFSET: u32 = 32;
export const ROUTE_STEP_PATH_VALIDATION_RESULT_BYTE_LENGTH: u32 = 40;

export const ROUTE_STEP_SEARCH_INPUT_CONTEXT_POINTER_OFFSET: u32 = 0;
export const ROUTE_STEP_SEARCH_INPUT_START_X_OFFSET: u32 = 8;
export const ROUTE_STEP_SEARCH_INPUT_START_Y_OFFSET: u32 = 16;
export const ROUTE_STEP_SEARCH_INPUT_TARGET_X_OFFSET: u32 = 24;
export const ROUTE_STEP_SEARCH_INPUT_TARGET_Y_OFFSET: u32 = 32;
export const ROUTE_STEP_SEARCH_INPUT_COLLECT_PREVIEWS_OFFSET: u32 = 40;
export const ROUTE_STEP_SEARCH_INPUT_RESOLVED_Y_OFFSET: u32 = 48;
export const ROUTE_STEP_SEARCH_INPUT_STATE_SIGN_OFFSET: u32 = 56;
export const ROUTE_STEP_SEARCH_INPUT_STATE_POINTER_OFFSET: u32 = 60;
export const ROUTE_STEP_SEARCH_INPUT_STATE_COUNT_OFFSET: u32 = 64;
export const ROUTE_STEP_SEARCH_INPUT_EXACT_START_X_OFFSET: u32 = 72;
export const ROUTE_STEP_SEARCH_INPUT_EXACT_START_Y_OFFSET: u32 = 80;
export const ROUTE_STEP_SEARCH_INPUT_EXACT_TARGET_X_OFFSET: u32 = 88;
export const ROUTE_STEP_SEARCH_INPUT_EXACT_TARGET_Y_OFFSET: u32 = 96;
export const ROUTE_STEP_SEARCH_INPUT_BYTE_LENGTH: u32 = 104;

export const ROUTE_STEP_SEARCH_RESULT_MAGIC: u32 = 0x5354_4854;
export const ROUTE_STEP_SEARCH_RESULT_STATUS_NO_ROUTE: u32 = 0;
export const ROUTE_STEP_SEARCH_RESULT_STATUS_SUCCESS: u32 = 1;
export const ROUTE_STEP_SEARCH_RESULT_MAGIC_OFFSET: u32 = 0;
export const ROUTE_STEP_SEARCH_RESULT_STATUS_OFFSET: u32 = 4;
export const ROUTE_STEP_SEARCH_RESULT_PATH_X_POINTER_OFFSET: u32 = 8;
export const ROUTE_STEP_SEARCH_RESULT_PATH_Y_POINTER_OFFSET: u32 = 12;
export const ROUTE_STEP_SEARCH_RESULT_PATH_LENGTH_OFFSET: u32 = 16;
export const ROUTE_STEP_SEARCH_RESULT_PREVIEW_POINTER_OFFSET: u32 = 20;
export const ROUTE_STEP_SEARCH_RESULT_PREVIEW_COUNT_OFFSET: u32 = 24;
export const ROUTE_STEP_SEARCH_RESULT_EXPANSION_COUNT_OFFSET: u32 = 28;
export const ROUTE_STEP_SEARCH_RESULT_RESOLVED_Y_OFFSET: u32 = 32;
export const ROUTE_STEP_SEARCH_RESULT_STATE_SIGN_OFFSET: u32 = 40;
export const ROUTE_STEP_SEARCH_RESULT_STATE_POINTER_OFFSET: u32 = 44;
export const ROUTE_STEP_SEARCH_RESULT_STATE_COUNT_OFFSET: u32 = 48;
export const ROUTE_STEP_SEARCH_RESULT_BYTE_LENGTH: u32 = 56;

export const ROUTE_PREVIEW_POINTS_X_POINTER_OFFSET: u32 = 0;
export const ROUTE_PREVIEW_POINTS_Y_POINTER_OFFSET: u32 = 4;
export const ROUTE_PREVIEW_POINT_COUNT_OFFSET: u32 = 8;
export const ROUTE_PREVIEW_ACCEPTED_INDEXES_POINTER_OFFSET: u32 = 12;
export const ROUTE_PREVIEW_ACCEPTED_INDEXES_LENGTH_OFFSET: u32 = 16;
export const ROUTE_PREVIEW_BEST_PATH_INDEXES_POINTER_OFFSET: u32 = 20;
export const ROUTE_PREVIEW_BEST_PATH_INDEXES_LENGTH_OFFSET: u32 = 24;
export const ROUTE_PREVIEW_CANDIDATE_INDEXES_POINTER_OFFSET: u32 = 28;
export const ROUTE_PREVIEW_CANDIDATE_INDEXES_LENGTH_OFFSET: u32 = 32;
export const ROUTE_PREVIEW_CURRENT_INDEX_OFFSET: u32 = 36;
export const ROUTE_PREVIEW_FLAGS_OFFSET: u32 = 40;
export const ROUTE_PREVIEW_FLAG_MIRRORED: u32 = 1;
export const ROUTE_PREVIEW_BYTE_LENGTH: u32 = 48;

export const ROUTE_BOUNDARY_EDGE_RECORD_U32_LENGTH: u32 = 5;

// Coarse smart/one-click composition commands. These records deliberately carry
// only immutable flat data; formula/trajectory and route contexts remain owned
// by the same WASM instance and are referenced by pointers below the arena.
export const SMART_INPUT_MAGIC: u32 = 0x534d_4152;
export const SMART_INPUT_VERSION: u32 = 4;
export const SMART_INPUT_FLAG_DELETE_OPTIMIZATION: u32 = 1;
export const SMART_INPUT_FLAG_ROUTE_CONTEXT_VALIDATION: u32 = 2;
export const SMART_INPUT_FLAG_GRAPH_VALIDATION: u32 = 4;
export const SMART_INPUT_FLAG_TRAJECTORY_VALIDATION: u32 = 8;
/** Allows trajectory-aware callers to remove the final generated control point. */
export const SMART_INPUT_FLAG_TERMINAL_POINT_DELETION: u32 = 16;
export const SMART_INPUT_MAGIC_OFFSET: u32 = 0;
export const SMART_INPUT_VERSION_OFFSET: u32 = 4;
export const SMART_INPUT_FLAGS_OFFSET: u32 = 8;
export const SMART_INPUT_POINTS_X_POINTER_OFFSET: u32 = 12;
export const SMART_INPUT_POINTS_Y_POINTER_OFFSET: u32 = 16;
export const SMART_INPUT_POINT_COUNT_OFFSET: u32 = 20;
export const SMART_INPUT_SOURCE_POINT_COUNT_OFFSET: u32 = 24;
export const SMART_INPUT_TARGET_X_OFFSET: u32 = 28;
export const SMART_INPUT_TARGET_Y_OFFSET: u32 = 36;
export const SMART_INPUT_TARGET_RADIUS_OFFSET: u32 = 44;
export const SMART_INPUT_ROUTE_POINTS_X_POINTER_OFFSET: u32 = 52;
export const SMART_INPUT_ROUTE_POINTS_Y_POINTER_OFFSET: u32 = 56;
export const SMART_INPUT_ROUTE_CONTEXT_POINTER_OFFSET: u32 = 60;
/** Continuous Graphwar x values paired with the quantized route points. */
export const SMART_INPUT_ROUTE_GRAPH_X_POINTER_OFFSET: u32 = 64;
export const SMART_INPUT_TRAJECTORY_COMMAND_POINTER_OFFSET: u32 = 72;
export const SMART_INPUT_TRAJECTORY_COMMAND_BYTE_LENGTH_OFFSET: u32 = 76;
/** Source point indexes that the smart deletion loop must retain. */
export const SMART_INPUT_PROTECTED_POINT_INDEXES_POINTER_OFFSET: u32 = 80;
export const SMART_INPUT_PROTECTED_POINT_INDEX_COUNT_OFFSET: u32 = 84;
export const SMART_INPUT_BYTE_LENGTH: u32 = 88;

export const SMART_RESULT_MAGIC: u32 = 0x534d_5253;
export const SMART_RESULT_STATUS_FAILURE: u32 = 0;
export const SMART_RESULT_STATUS_SUCCESS: u32 = 1;
export const SMART_RESULT_MAGIC_OFFSET: u32 = 0;
export const SMART_RESULT_STATUS_OFFSET: u32 = 4;
export const SMART_RESULT_POINTS_X_POINTER_OFFSET: u32 = 8;
export const SMART_RESULT_POINTS_Y_POINTER_OFFSET: u32 = 12;
export const SMART_RESULT_POINT_COUNT_OFFSET: u32 = 16;
export const SMART_RESULT_REMOVED_POINT_COUNT_OFFSET: u32 = 20;
export const SMART_RESULT_VALIDATED_FLAG_OFFSET: u32 = 24;
export const SMART_RESULT_FAILURE_REASON_OFFSET: u32 = 28;
export const SMART_RESULT_FAILURE_REASON_NONE: u32 = 0;
export const SMART_RESULT_FAILURE_REASON_TARGET: u32 = 1;
export const SMART_RESULT_FAILURE_REASON_GRAPH_RULE: u32 = 2;
export const SMART_RESULT_FAILURE_REASON_ROUTE_OBSTACLE: u32 = 3;
export const SMART_RESULT_FAILURE_REASON_TRAJECTORY: u32 = 4;
export const SMART_RESULT_OUTPUT_GRAPH_X_POINTER_OFFSET: u32 = 32;
export const SMART_RESULT_OUTPUT_ROUTE_X_POINTER_OFFSET: u32 = 36;
export const SMART_RESULT_OUTPUT_ROUTE_Y_POINTER_OFFSET: u32 = 40;
export const SMART_RESULT_OUTPUT_EVIDENCE_COUNT_OFFSET: u32 = 44;
export const SMART_RESULT_VALIDATION_ROLE_OFFSET: u32 = 48;
export const SMART_RESULT_VALIDATION_ROLE_NONE: u32 = 0;
export const SMART_RESULT_VALIDATION_ROLE_ROUTE_ONLY: u32 = 1;
export const SMART_RESULT_VALIDATION_ROLE_TRAJECTORY: u32 = 2;
export const SMART_RESULT_DETAIL_FLAGS_OFFSET: u32 = 52;
export const SMART_RESULT_DETAIL_FLAG_BLOCKED_POINT: u32 = 1;
export const SMART_RESULT_TARGET_X_OFFSET: u32 = 56;
export const SMART_RESULT_TARGET_Y_OFFSET: u32 = 64;
export const SMART_RESULT_TARGET_RADIUS_OFFSET: u32 = 72;
export const SMART_RESULT_BLOCKED_POINT_X_OFFSET: u32 = 80;
export const SMART_RESULT_BLOCKED_POINT_Y_OFFSET: u32 = 88;
/** Counts copied from the same trajectory replay that classified a smart failure/success. */
export const SMART_RESULT_REACHED_REQUIRED_TARGET_COUNT_OFFSET: u32 = 96;
export const SMART_RESULT_REACHED_TARGET_COUNT_OFFSET: u32 = 100;
/** Source input indexes retained by the deletion loop, in output order. */
export const SMART_RESULT_OUTPUT_SOURCE_INDEXES_POINTER_OFFSET: u32 = 104;
export const SMART_RESULT_BYTE_LENGTH: u32 = 112;

export const ONE_CLICK_INPUT_MAGIC: u32 = 0x4f_434c_52;
export const ONE_CLICK_INPUT_VERSION: u32 = 1;
export const ONE_CLICK_INPUT_FLAG_DELETE_OPTIMIZATION: u32 = 1;
export const ONE_CLICK_INPUT_FLAG_STEP_STATEFUL: u32 = 2;
export const ONE_CLICK_INPUT_FLAG_TARGET_ORDER_DESCENDING: u32 = 4;
export const ONE_CLICK_INPUT_FLAG_EXPLICIT_DAG: u32 = 8;
export const ONE_CLICK_INPUT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_INPUT_VERSION_OFFSET: u32 = 4;
export const ONE_CLICK_INPUT_FLAGS_OFFSET: u32 = 8;
export const ONE_CLICK_INPUT_CANDIDATE_X_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_INPUT_CANDIDATE_Y_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_INPUT_CANDIDATE_RADIUS_POINTER_OFFSET: u32 = 20;
export const ONE_CLICK_INPUT_CANDIDATE_FLAGS_POINTER_OFFSET: u32 = 24;
export const ONE_CLICK_INPUT_CANDIDATE_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_INPUT_PATH_X_POINTER_OFFSET: u32 = 32;
export const ONE_CLICK_INPUT_PATH_Y_POINTER_OFFSET: u32 = 36;
export const ONE_CLICK_INPUT_PATH_COUNT_OFFSET: u32 = 40;
export const ONE_CLICK_INPUT_ROUTE_CONTEXT_POINTER_OFFSET: u32 = 44;
export const ONE_CLICK_INPUT_REQUEST_NONCE_OFFSET: u32 = 48;
export const ONE_CLICK_INPUT_VERTICAL_VARIATION_SCALE_OFFSET: u32 = 56;
/** Optional extension carrying the already-quantized forward-plane target columns. */
export const ONE_CLICK_INPUT_TARGET_ORDER_KEYS_POINTER_OFFSET: u32 = 64;
export const ONE_CLICK_INPUT_TARGET_ORDER_KEYS_COUNT_OFFSET: u32 = 68;
export const ONE_CLICK_INPUT_DAG_JOB_POINTER_OFFSET: u32 = 72;
export const ONE_CLICK_INPUT_DAG_JOB_COUNT_OFFSET: u32 = 76;
export const ONE_CLICK_INPUT_DAG_NODE_IDS_POINTER_OFFSET: u32 = 80;
export const ONE_CLICK_INPUT_DAG_NODE_IDS_COUNT_OFFSET: u32 = 84;
export const ONE_CLICK_INPUT_DAG_NODE_COUNT_OFFSET: u32 = 88;
/** Optional atomic Step node evidence accompanying an explicit stateful DAG. */
export const ONE_CLICK_INPUT_DAG_NODE_TARGETS_POINTER_OFFSET: u32 = 92;
export const ONE_CLICK_INPUT_DAG_NODE_RESOLVED_Y_POINTER_OFFSET: u32 = 96;
export const ONE_CLICK_INPUT_DAG_NODE_KEY_OFFSETS_POINTER_OFFSET: u32 = 100;
export const ONE_CLICK_INPUT_DAG_NODE_KEY_LENGTHS_POINTER_OFFSET: u32 = 104;
export const ONE_CLICK_INPUT_DAG_NODE_KEY_BYTES_POINTER_OFFSET: u32 = 108;
export const ONE_CLICK_INPUT_DAG_NODE_KEY_BYTE_LENGTH_OFFSET: u32 = 112;
export const ONE_CLICK_INPUT_DAG_NODE_EVIDENCE_COUNT_OFFSET: u32 = 116;
export const ONE_CLICK_INPUT_LEGACY_BYTE_LENGTH: u32 = 64;
export const ONE_CLICK_INPUT_COLUMNS_BYTE_LENGTH: u32 = 72;
export const ONE_CLICK_INPUT_BYTE_LENGTH: u32 = 96;
export const ONE_CLICK_INPUT_EVIDENCE_BYTE_LENGTH: u32 = 120;

export const ONE_CLICK_RESULT_MAGIC: u32 = 0x4f_4352_53;
export const ONE_CLICK_RESULT_STATUS_COMPLETE: u32 = 0;
export const ONE_CLICK_RESULT_STATUS_WAITING_EDGE_BATCH: u32 = 1;
export const ONE_CLICK_RESULT_STATUS_FAILURE: u32 = 2;
export const ONE_CLICK_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_RESULT_SESSION_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_RESULT_EDGE_JOB_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_RESULT_EDGE_JOB_COUNT_OFFSET: u32 = 16;
export const ONE_CLICK_RESULT_TARGET_ORDER_POINTER_OFFSET: u32 = 20;
export const ONE_CLICK_RESULT_TARGET_COUNT_OFFSET: u32 = 24;
export const ONE_CLICK_RESULT_PATH_X_POINTER_OFFSET: u32 = 28;
export const ONE_CLICK_RESULT_PATH_Y_POINTER_OFFSET: u32 = 32;
export const ONE_CLICK_RESULT_PATH_COUNT_OFFSET: u32 = 36;
export const ONE_CLICK_RESULT_SELECTED_EDGE_COUNT_OFFSET: u32 = 40;
export const ONE_CLICK_RESULT_NONCE_OFFSET: u32 = 44;
export const ONE_CLICK_RESULT_REQUEST_NONCE_OFFSET: u32 = 48;
/** Ordered selected edge ids, from the retained source path to the final target. */
export const ONE_CLICK_RESULT_SELECTED_EDGE_IDS_POINTER_OFFSET: u32 = 52;
/** Route-context validation status is explicit; zero means no route evidence. */
export const ONE_CLICK_RESULT_ROUTE_VALIDATION_OFFSET: u32 = 56;
export const ONE_CLICK_RESULT_ROUTE_VALIDATION_NONE: u32 = 0;
export const ONE_CLICK_RESULT_ROUTE_VALIDATION_VALIDATED: u32 = 1;
export const ONE_CLICK_RESULT_REMOVED_POINT_COUNT_OFFSET: u32 = 60;
export const ONE_CLICK_RESULT_BYTE_LENGTH: u32 = 64;

// Edge jobs are flat records: three leading u32 fields for id/from/to, four f64
// endpoint fields, then two u32 node identities. Results carry the same id plus
// a route point span, letting the session consume completion in any order.
export const ONE_CLICK_EDGE_JOB_U32_LENGTH: u32 = 5;
export const ONE_CLICK_EDGE_JOB_F64_LENGTH: u32 = 4;
export const ONE_CLICK_EDGE_JOB_FROM_NODE_OFFSET: u32 = 48;
export const ONE_CLICK_EDGE_JOB_TO_NODE_OFFSET: u32 = 52;
export const ONE_CLICK_EDGE_JOB_BYTE_LENGTH: u32 = 56;
/**
 * Edge results keep the legacy route/session fields at offsets 0..27. Stateful
 * Step results append one atomic successor evidence record; stateless and
 * unreachable results leave this extension zeroed.
 */
export const ONE_CLICK_EDGE_RESULT_STATE_KEY_POINTER_OFFSET: u32 = 28;
export const ONE_CLICK_EDGE_RESULT_STATE_KEY_LENGTH_OFFSET: u32 = 32;
export const ONE_CLICK_EDGE_RESULT_TARGET_INDEX_OFFSET: u32 = 36;
export const ONE_CLICK_EDGE_RESULT_RESOLVED_Y_OFFSET: u32 = 40;
export const ONE_CLICK_EDGE_RESULT_BYTE_LENGTH: u32 = 48;
export const ONE_CLICK_SESSION_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_SESSION_MAGIC: u32 = 0x4f_4353_53;
export const ONE_CLICK_SESSION_NONCE_OFFSET: u32 = 4;
export const ONE_CLICK_SESSION_PHASE_OFFSET: u32 = 8;
export const ONE_CLICK_SESSION_FLAGS_OFFSET: u32 = 12;
export const ONE_CLICK_SESSION_TARGET_X_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_SESSION_TARGET_Y_POINTER_OFFSET: u32 = 20;
export const ONE_CLICK_SESSION_TARGET_RADIUS_POINTER_OFFSET: u32 = 24;
export const ONE_CLICK_SESSION_TARGET_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_SESSION_PATH_X_POINTER_OFFSET: u32 = 32;
export const ONE_CLICK_SESSION_PATH_Y_POINTER_OFFSET: u32 = 36;
export const ONE_CLICK_SESSION_PATH_COUNT_OFFSET: u32 = 40;
export const ONE_CLICK_SESSION_JOB_POINTER_OFFSET: u32 = 44;
export const ONE_CLICK_SESSION_JOB_COUNT_OFFSET: u32 = 48;
export const ONE_CLICK_SESSION_RESULT_PATH_X_POINTER_OFFSET: u32 = 52;
export const ONE_CLICK_SESSION_RESULT_PATH_Y_POINTER_OFFSET: u32 = 56;
export const ONE_CLICK_SESSION_RESULT_PATH_COUNT_OFFSET: u32 = 60;
export const ONE_CLICK_SESSION_COMPLETED_FLAGS_POINTER_OFFSET: u32 = 64;
export const ONE_CLICK_SESSION_COMPLETED_COUNT_OFFSET: u32 = 68;
export const ONE_CLICK_SESSION_ROUTE_POINTER_OFFSET: u32 = 72;
export const ONE_CLICK_SESSION_ROUTE_POINT_COUNT_POINTER_OFFSET: u32 = 76;
export const ONE_CLICK_SESSION_ROUTE_CAPACITY_OFFSET: u32 = 80;
export const ONE_CLICK_SESSION_TARGET_ORDER_POINTER_OFFSET: u32 = 84;
export const ONE_CLICK_SESSION_REQUEST_NONCE_OFFSET: u32 = 88;
export const ONE_CLICK_SESSION_VERTICAL_VARIATION_SCALE_OFFSET: u32 = 96;
export const ONE_CLICK_SESSION_NODE_COUNT_OFFSET: u32 = 104;
export const ONE_CLICK_SESSION_ROUTE_CONTEXT_POINTER_OFFSET: u32 = 108;
/** Retained Step node evidence, indexed by node id for explicit stateful DAGs. */
export const ONE_CLICK_SESSION_NODE_TARGETS_POINTER_OFFSET: u32 = 120;
export const ONE_CLICK_SESSION_NODE_RESOLVED_Y_POINTER_OFFSET: u32 = 124;
export const ONE_CLICK_SESSION_NODE_KEY_OFFSETS_POINTER_OFFSET: u32 = 128;
export const ONE_CLICK_SESSION_NODE_KEY_LENGTHS_POINTER_OFFSET: u32 = 132;
export const ONE_CLICK_SESSION_NODE_KEY_BYTES_POINTER_OFFSET: u32 = 136;
export const ONE_CLICK_SESSION_NODE_KEY_BYTE_LENGTH_OFFSET: u32 = 140;
export const ONE_CLICK_SESSION_NODE_EVIDENCE_COUNT_OFFSET: u32 = 144;
/** Number of accepted stateful edge batches; monotonic while the session waits. */
export const ONE_CLICK_SESSION_LAYER_CURSOR_OFFSET: u32 = 148;
export const ONE_CLICK_SESSION_BYTE_LENGTH: u32 = 160;
export const ONE_CLICK_SESSION_PHASE_WAITING_EDGE_BATCH: u32 = 1;
export const ONE_CLICK_SESSION_PHASE_COMPLETE: u32 = 2;
export const ONE_CLICK_RESUME_SESSION_POINTER_OFFSET: u32 = 0;
export const ONE_CLICK_RESUME_NONCE_OFFSET: u32 = 4;
export const ONE_CLICK_RESUME_WORK_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_RESUME_WORK_COUNT_OFFSET: u32 = 12;
export const ONE_CLICK_RESUME_BYTE_LENGTH: u32 = 16;

// Target assignment is a separate versioned command so existing one-click
// session callers keep their legacy/column/DAG record sizes unchanged.
export const ONE_CLICK_ASSIGN_INPUT_MAGIC: u32 = 0x4f_4341_53;
export const ONE_CLICK_ASSIGN_INPUT_VERSION: u32 = 1;
export const ONE_CLICK_ASSIGN_INPUT_FLAG_MIRRORED: u32 = 1;
export const ONE_CLICK_ASSIGN_INPUT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_ASSIGN_INPUT_VERSION_OFFSET: u32 = 4;
export const ONE_CLICK_ASSIGN_INPUT_FLAGS_OFFSET: u32 = 8;
export const ONE_CLICK_ASSIGN_INPUT_CANDIDATE_X_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_ASSIGN_INPUT_CANDIDATE_Y_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_ASSIGN_INPUT_CANDIDATE_RADIUS_POINTER_OFFSET: u32 = 20;
export const ONE_CLICK_ASSIGN_INPUT_CANDIDATE_SOURCE_INDEX_POINTER_OFFSET: u32 = 24;
export const ONE_CLICK_ASSIGN_INPUT_CANDIDATE_COUNT_OFFSET: u32 = 28;
export const ONE_CLICK_ASSIGN_INPUT_PATH_TAIL_X_OFFSET: u32 = 32;
export const ONE_CLICK_ASSIGN_INPUT_PATH_TAIL_Y_OFFSET: u32 = 40;
export const ONE_CLICK_ASSIGN_INPUT_BOUNDS_RECT_X_OFFSET: u32 = 48;
export const ONE_CLICK_ASSIGN_INPUT_BOUNDS_RECT_Y_OFFSET: u32 = 56;
export const ONE_CLICK_ASSIGN_INPUT_BOUNDS_RECT_WIDTH_OFFSET: u32 = 64;
export const ONE_CLICK_ASSIGN_INPUT_BOUNDS_RECT_HEIGHT_OFFSET: u32 = 72;
export const ONE_CLICK_ASSIGN_INPUT_USABLE_RECT_X_OFFSET: u32 = 80;
export const ONE_CLICK_ASSIGN_INPUT_USABLE_RECT_Y_OFFSET: u32 = 88;
export const ONE_CLICK_ASSIGN_INPUT_USABLE_RECT_WIDTH_OFFSET: u32 = 96;
export const ONE_CLICK_ASSIGN_INPUT_USABLE_RECT_HEIGHT_OFFSET: u32 = 104;
export const ONE_CLICK_ASSIGN_INPUT_BOUNDARY_EXPANSION_OFFSET: u32 = 112;
export const ONE_CLICK_ASSIGN_INPUT_BYTE_LENGTH: u32 = 120;

export const ONE_CLICK_ASSIGN_RESULT_MAGIC: u32 = 0x4f_4341_52;
export const ONE_CLICK_ASSIGN_RESULT_STATUS_SUCCESS: u32 = 0;
export const ONE_CLICK_ASSIGN_RESULT_MAGIC_OFFSET: u32 = 0;
export const ONE_CLICK_ASSIGN_RESULT_STATUS_OFFSET: u32 = 4;
export const ONE_CLICK_ASSIGN_RESULT_SOURCE_INDEX_POINTER_OFFSET: u32 = 8;
export const ONE_CLICK_ASSIGN_RESULT_ROUTE_X_POINTER_OFFSET: u32 = 12;
export const ONE_CLICK_ASSIGN_RESULT_ROUTE_Y_POINTER_OFFSET: u32 = 16;
export const ONE_CLICK_ASSIGN_RESULT_COUNT_OFFSET: u32 = 20;
export const ONE_CLICK_ASSIGN_RESULT_BYTE_LENGTH: u32 = 24;
