name: PR compat-finder package Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

concurrency:
  group: pr-compat-finder-build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build compat-finder Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1
      - name: Build with composite action
        uses: ./.github/actions/build-package
        with:
          build-command: pnpm compat-finder:build
          artifact-name: compat-finder-dist
          artifact-path: packages/compat-finder/dist
